logoText = "nya"
logoType = "short"
logo = false
description = "個人的に勉強して面白かったことやCTFのwriteup等を書き連ねていきます。"
custom_css = []
custom_js = []
useFaviconGenerator = false
languagedir = "ltr"

themeOptions = ["light", "dark"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase"]
notAllowedTypesInArchive = ["about", "talks", "showcase"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal"
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false

homeHeaderType = "text"

showMobileMenuTerms = ["tags"]

enableThemeChange = true

enableBreadcrumb = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "card"
archiveGroupByDate = "2006"
archivePaginate = 3
paginateWindow = 1
talksPaginate = 8
talksGroupByDate = "2006"

myname = "mitsu"
email = "kyomu@gmail.comjanaiyo"
whoami = "neko"
bioImageUrl = ""
useGravatar = false
location = "the kingdom of neko"
organization = "kyomu"
link = "https://github.com/mitsu1119"

enableBio = true # in home page sidebar
enableBioImage = true # in home page sidebar
enableSidebar = true # Set to false to create the full width of the content.
enableSidebarTags = true # if you want to use tags.
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true # single page table of contents, you can replace this param to toc(toc = true)
hideToc = false # Hide or Show toc
tocPosition = "inner" # inner, outer
tocFolding = false
enableTocSwitch = true # single page table of contents visibility switch
itemsPerCategory = 5 # maximum number of posts shown in the sidebar.
sidebarPosition = "right" # bio, profile component layout position
tocLevels = ["h2", "h3", "h4"] # minimum h2, maximum h4 in your article
enableSidebarPostsByOrder = false # another lists in the sidebar

# footer
showPoweredBy = true # show footer text: Powered by Hugo and Zzo theme
showFeedLinks = true # RSS Feed 
showSocialLinks = true # email, facebook, twitter ...
enableLangChange = true # show button at bottom left of footer.

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = "" # alternative of google analytics
enableBusuanzi = false # if set true, total page view, total unique visitors show up in the footer.
busuanziSiteUV = true # unique visitors (total number of visitors)
busuanziSitePV = true # site total page view count
busuanziPagePV = true # post view count

# comment
enableComment = true
disqus_shortname = "" 
commento = false

[socialOptions]
twitter = "https://twitter.com/meowricator"
github = "https://github.com/mitsu1119"

